"""Pipeline parameters as TOML: load, dump and ``key=value`` overrides.

The file mirrors :class:`~flat_segments.params.PipelineParams`::

    [profile]
    step_m = 5.0

    [detection.flat]
    max_local_grade_pct = 1.5

Missing keys keep their default, unknown keys are errors (typos must not be
silently ignored). ``configs/default.toml`` is the dump of the defaults.
"""

from __future__ import annotations

import dataclasses
import tomllib
import typing
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, Final

from flat_segments.params import PipelineParams

#: Short prefixes accepted in overrides, as used in docs/algorithm.md.
SHORTCUTS: Final[Mapping[str, str]] = {
    "flat": "detection.flat",
    "climb": "detection.climb",
    "dedup": "detection.dedup",
}

HEADER: Final = (
    "# flat-segments pipeline parameters.\n"
    "# Generated by `flat-segments config`; every value is documented in\n"
    "# docs/algorithm.md (section 13). Remove a key to keep its default.\n"
)


class ConfigError(ValueError):
    """Invalid configuration file or override."""


def _build(cls: type[Any], data: Any, path: str) -> Any:
    if not isinstance(data, Mapping):
        raise ConfigError(f"{path or 'root'}: expected a table, got {data!r}")
    hints = typing.get_type_hints(cls)
    fields = {f.name for f in dataclasses.fields(cls)}
    unknown = sorted(set(data) - fields)
    if unknown:
        names = ", ".join(f"{path}{name}" for name in unknown)
        raise ConfigError(f"unknown parameter(s): {names}")
    kwargs = {name: _convert(hints[name], value, f"{path}{name}") for name, value in data.items()}
    try:
        return cls(**kwargs)
    except ValueError as error:
        raise ConfigError(str(error)) from error


def _convert(hint: Any, value: Any, path: str) -> Any:
    if dataclasses.is_dataclass(hint) and isinstance(hint, type):
        return _build(hint, value, f"{path}.")
    if hint is float:
        if isinstance(value, bool) or not isinstance(value, int | float):
            raise ConfigError(f"{path}: expected a number, got {value!r}")
        return float(value)
    if typing.get_origin(hint) is tuple:
        if not isinstance(value, list | tuple) or not all(
            isinstance(v, int | float) and not isinstance(v, bool) for v in value
        ):
            raise ConfigError(f"{path}: expected a list of numbers, got {value!r}")
        return tuple(float(v) for v in value)
    raise ConfigError(f"{path}: unsupported parameter type {hint}")  # pragma: no cover


def params_from_dict(data: Mapping[str, Any]) -> PipelineParams:
    """Build parameters from a nested mapping (missing keys keep defaults).

    Raises:
        ConfigError: On unknown keys, wrong types or invalid values.
    """
    params: PipelineParams = _build(PipelineParams, data, "")
    return params


def params_to_dict(params: PipelineParams) -> dict[str, Any]:
    """Nested mapping of all parameters (tuples become lists)."""

    def convert(value: Any) -> Any:
        if isinstance(value, dict):
            return {k: convert(v) for k, v in value.items()}
        if isinstance(value, tuple):
            return list(value)
        return value

    result: dict[str, Any] = convert(dataclasses.asdict(params))
    return result


def _format(value: Any) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(_format(v) for v in value) + "]"
    return repr(float(value))


def params_to_toml(params: PipelineParams) -> str:
    """Serialise parameters to TOML (the format read by :func:`load_params`)."""
    lines = [HEADER]

    def dump(table: Mapping[str, Any], prefix: str) -> None:
        scalars = {k: v for k, v in table.items() if not isinstance(v, dict)}
        if scalars:
            lines.append(f"[{prefix}]")
            lines.extend(f"{key} = {_format(value)}" for key, value in scalars.items())
            lines.append("")
        for key, value in table.items():
            if isinstance(value, dict):
                dump(value, f"{prefix}.{key}" if prefix else key)

    dump(params_to_dict(params), "")
    return "\n".join(lines).rstrip() + "\n"


def parse_override(text: str) -> tuple[list[str], Any]:
    """Parse ``"flat.max_local_grade_pct=1.5"`` into a key path and a TOML value.

    Raises:
        ConfigError: If the text is not ``key=value`` or the value is not TOML.
    """
    key, sep, raw = text.partition("=")
    key, raw = key.strip(), raw.strip()
    if not sep or not key or not raw:
        raise ConfigError(f"expected key=value, got {text!r}")
    head, _, rest = key.partition(".")
    if head in SHORTCUTS:
        key = f"{SHORTCUTS[head]}.{rest}" if rest else SHORTCUTS[head]
    try:
        value = tomllib.loads(f"value = {raw}")["value"]
    except tomllib.TOMLDecodeError as error:
        raise ConfigError(f"{key}: invalid value {raw!r}") from error
    return key.split("."), value


def apply_overrides(params: PipelineParams, overrides: Sequence[str]) -> PipelineParams:
    """Return ``params`` with ``key=value`` overrides applied.

    Raises:
        ConfigError: On malformed overrides or invalid resulting parameters.
    """
    if not overrides:
        return params
    data = params_to_dict(params)
    for text in overrides:
        path, value = parse_override(text)
        table = data
        for part in path[:-1]:
            if not isinstance(table.get(part), dict):
                raise ConfigError(f"unknown parameter group: {'.'.join(path[:-1])}")
            table = table[part]
        if path[-1] not in table or isinstance(table[path[-1]], dict):
            raise ConfigError(f"unknown parameter: {'.'.join(path)}")
        table[path[-1]] = value
    return params_from_dict(data)


def load_params(path: Path | None = None, overrides: Sequence[str] = ()) -> PipelineParams:
    """Defaults, updated by an optional TOML file, then by overrides.

    Raises:
        ConfigError: On any invalid input.
    """
    params = PipelineParams()
    if path is not None:
        try:
            data = tomllib.loads(path.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError as error:
            raise ConfigError(f"{path}: {error}") from error
        params = params_from_dict(data)
    return apply_overrides(params, overrides)
